services:
    rabbitmq:
        image: rabbitmq:4.0.5-management
        container_name: rabbitmq
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            RABBITMQ_DEFAULT_USER: guest    
            RABBITMQ_DEFAULT_PASS: guest    
    notification:
        image: node:23.2.0-alpine
        container_name: notification-service
        ports:
            - "3000:3000"
        volumes:
            - .:/app
        working_dir: /app
        command: sh -c "apk add --no-cache python3 py3-pip make g++ && npm install --build-from-source && npm run dev"
        environment:
            - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
        depends_on:
            - rabbitmq